export const SKILL_LEVELS = {
  EXPERT: "Expert",
  ADVANCED: "Advanced",
  INTERMEDIATE: "Intermediate",
  BEGINNER: "Beginner",
} as const;

export const SKILL_LEVEL_TO_PERCENTAGE = {
  [SKILL_LEVELS.BEGINNER]: 25,
  [SKILL_LEVELS.INTERMEDIATE]: 50,
  [SKILL_LEVELS.ADVANCED]: 75,
  [SKILL_LEVELS.EXPERT]: 100,
} as const;

export const SKILL_LEVEL_PRIORITY = {
  [SKILL_LEVELS.EXPERT]: 4,
  [SKILL_LEVELS.ADVANCED]: 3,
  [SKILL_LEVELS.INTERMEDIATE]: 2,
  [SKILL_LEVELS.BEGINNER]: 1,
} as const;

export const SKILL_LEVEL_COLORS = {
  [SKILL_LEVELS.EXPERT]: "#10B981",
  [SKILL_LEVELS.ADVANCED]: "#F59E0B",
  [SKILL_LEVELS.INTERMEDIATE]: "#3B82F6",
  [SKILL_LEVELS.BEGINNER]: "#94A3B8",
} as const;

export const SKILL_LEGEND_LEVELS = [
  {
    name: SKILL_LEVELS.EXPERT,
    percentage: SKILL_LEVEL_TO_PERCENTAGE[SKILL_LEVELS.EXPERT],
    color: SKILL_LEVEL_COLORS[SKILL_LEVELS.EXPERT],
  },
  {
    name: SKILL_LEVELS.ADVANCED,
    percentage: SKILL_LEVEL_TO_PERCENTAGE[SKILL_LEVELS.ADVANCED],
    color: SKILL_LEVEL_COLORS[SKILL_LEVELS.ADVANCED],
  },
  {
    name: SKILL_LEVELS.INTERMEDIATE,
    percentage: SKILL_LEVEL_TO_PERCENTAGE[SKILL_LEVELS.INTERMEDIATE],
    color: SKILL_LEVEL_COLORS[SKILL_LEVELS.INTERMEDIATE],
  },
  {
    name: SKILL_LEVELS.BEGINNER,
    percentage: SKILL_LEVEL_TO_PERCENTAGE[SKILL_LEVELS.BEGINNER],
    color: SKILL_LEVEL_COLORS[SKILL_LEVELS.BEGINNER],
  },
];

export const CHART_DEFAULTS = {
  MAX_SCALE: 100,
  MIN_SCALE: 0,
  STEP_SIZE: 25,
  MAIN_CHART_HEIGHT: 400,
  TECH_CHART_HEIGHT: 350,
  TOP_SKILLS_COUNT: 4,
} as const;
